config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
    get :autocomplete,on: :collection
    get :dropdown_sort,on: :collection
  end 
    

  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

   user ||= User.new
   if !user.id.nil?
      can :read, :all
      can :create, Comment
      can [:update, :destroy, :edit], Comment do |comment|
          comment && comment.user == user
       end
      can [:create,:autocomplete,:dropdown_sort], Post
      can [:update, :destroy, :edit], Post do |post|
          post && post.user == user
      end
    else
      can :read, Post
      can :autocomplete, Post
      can :dropdown_sort, Post 
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates_presence_of  :title,:body
  validates :body,length: {minimum: 10, maximum: 100}
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	validates_presence_of  :title,:body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action do
  	resource = controller_path.singularize.gsub('/','_').to_sym
  	method = "#{resource}_params"
  	params[resource] &&= send(method) if respond_to?(method,true)
  end
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment , only: [:edit, :update, :destroy]
  before_action :load_post , only: [:new, :create]
  load_and_authorize_resource
  respond_to :js,:html
  def new
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
  end
  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment.user = current_user

     @comment.update(comment_params)
        
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    def load_post
      @post = Post.find(params[:post_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :body,:rating, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :html, :js
  # GET /posts
  # GET /posts.json
  def index
    if params[:query].present?
      @posts = Post.where('title LIKE ?', "%#{params[:query]}%") 
    elsif params[:sort].present?
      case
        when "title" == params[:sort]
          @posts = Post.all.order("#{params[:sort]} asc")
        when "body" == params[:sort]
          @posts = Post.all.order("#{params[:sort]} asc")
        when "created_at" == params[:sort]
          @posts = Post.all.order("#{params[:sort]} desc")
      end
    else
      @user = current_user
      @posts = Post.all
    end
    respond_to do |format|
    format.html 
    format.js 
  end 
    
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @posts = Post.all
    @post = Post.new(post_params)
    @post.user= current_user
    @post.save
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @posts = Post.all
    @post.update(post_params)      
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @posts = Post.all
    @post.destroy
  end
  def autocomplete
    @posts = Post.order(:title).where("title LIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { 
        render json: @posts.map(&:title)
      }
    end
  end

  def dropdown_sort
    if params[:sort].present?
      case
        when "title" == params[:sort]
          @posts = Post.all.order("#{params[:sort]} asc")
        when "body" == params[:sort]
          @posts = Post.all.order("#{params[:sort]} asc")
        when "created_at" == params[:sort]
          @posts = Post.all.order("#{params[:sort]} desc")
      end
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<section class="panel">
	<h5><%= comment.title %> - <%= comment.user.email %></h5>
	<p><%= comment.body %></p>
	<p>
		<div class="star-rating" data-score=<%= comment.rating %>> </div>
	</p>
		<% if can? :update, comment %>
			<%= link_to 'Edit', edit_post_comment_path(@post,comment), :remote=> true, class: 'label label-warning lab-sx' %> |
		<% end %>
		<% if can? :destroy, comment %>
			<%= link_to 'Destroy', post_comment_path(@post , comment), method: :delete,:remote=> true, data: { confirm: 'Are you sure?' }, class: 'label label-danger btn-xs' %>
		<% end %>
</section>

<script>
	$('.star-rating').raty({
		path: '/assets/',
		readOnly: true,
		half:true,
		score: function() {
		return $(this).attr('data-score');
		}
	});
</script>

  

app/views/comments/_edit.html.erb
<h1>Editing comment</h1>
<%= form_for([@post,@comment], :remote=> true, :html=> {:class=> "form-inline"} ) do |f| %>
  <ul class="errors"></ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title ,:maxlength=>30, class: 'form-control'%>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body ,:maxlength=>100, class: 'form-control'%>
  </p>
  <p>
    <%= f.submit "Submit Comment", class: 'btn btn-success btn-sx' %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build], :remote=> true, :html=> {:class=> "form-inline"} ) do |f| %>
  <ul class="errors"></ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title ,:maxlength=>30, class: 'form-control'%>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body ,:maxlength=>100, class: 'form-control'%>
  </p>
  <p>
    <div id="star-rating"> </div>
  </p>
  <p>
    <%= f.submit "Submit Comment", class: 'btn btn-success btn-sx' %>
  </p>
<% end %>

app/views/comments/create.js.erb
$("ul.errors").html("")
<% if @comment.errors.any? %>
	<% @comment.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
	$("#comments").html("<%=j render @post.comments %>");
	$('#post_count').html('<%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');
	$('#new_comment')[0].reset();
<% end %>

app/views/comments/destroy.js.erb
$("#comments").html("<%=j render @post.comments %>");
$('#post_count').html('<%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');

app/views/comments/edit.js.erb
$.fancybox("<%= escape_javascript(render 'edit') %>",
  {
    openEffect: "fade",
    closeEffect: "fade",
    autoSize: true,
    minWidth: 1000,
    
  });

app/views/comments/new.html.erb
<section class="panel">
<h4 class="panel-heading">New comment</h4>

<%= render 'form' %>

<%= link_to 'Back', post_path( @comment[:post_id]), class: 'label label-danger lab-sx' %>
</section>

app/views/comments/update.js.erb
$("ul.errors").html("")
<% if @comment.errors.any? %>
	<% @comment.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
	$("#comments").html("<%=j render @post.comments %>");
	$.fancybox.close();
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Posts ", root_path , class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li><%= link_to "New Post", new_post_path, class: "active" %></li>
      <li><%= link_to "Acccout", edit_user_registration_path, class: "active" %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "active" %></li>
        
      <% else %>
      <li><%= link_to "Sign Up",new_user_registration_path, class: "active" %></li>
      <li><%= link_to "Sign In", user_session_path, class: "active" %></li>
        
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<html>
<head>
  <title>SmartMoviePractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= render 'layouts/header' %>
	<%= render 'layouts/messages' %>
	<%= yield %>
	<footer>
		<p>&copy; Ruby Effect 2015</p>
	</footer>

</div>

</body>
</html>

app/views/posts/_edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Post</h4>
      </div>
		<%= render 'form' %>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :title, class:"control-label" %>
      <div class="controls">
        <%= f.text_field :title,class:"form-control" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :body, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :body,class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>

app/views/posts/_new.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create new Post</h4>
      </div>
		<%= render 'form' %>
	</div>
</div>

app/views/posts/_post_list.html.erb
<% @posts.each do |post| %>
	<tr>
	  <td><%= post.title %></td>
	  <td><%= post.body %></td>
	  <td><%= link_to 'Show', post,:class=> "btn btn-default" %></td>
	  <% if can? :update, post %>
	  	<td><%= link_to 'Edit', edit_post_path(post), remote: true, :class=>"btn btn-info"%></td>
	  <% end %>
	  <% if can? :destroy, post %>
	  	<td><%= link_to 'Destroy', post, method: :delete, remote: true, :class=> "btn btn-danger", data: { confirm: 'Are you sure?' } %></td> <% end %>
	</tr>
<% end %>

app/views/posts/_save.js.erb
$("ul.errors").html("")
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#post_index").html("<%= escape_javascript(render 'post_list') %>")
  $("#post-modal").modal("hide")
<% end %>

app/views/posts/create.js.erb
<%= render "save" %>

app/views/posts/destroy.js.erb
$("#post_index").html("<%= j render :partial => 'post_list'%>");

app/views/posts/dropdown_sort.js.erb
$("#post_index").html("<%= j render :partial => 'post_list', :posts => @posts %>");

app/views/posts/edit.js.erb
$("#post-modal").html("<%= escape_javascript(render 'edit') %>")
$("#post-modal").modal("show")

app/views/posts/index.html.erb
<%= form_tag posts_path, :method => "get",:remote=> true, :id=> "theForm",:class=> "pull-right" do %>
    <%= text_field_tag :query, params[:query], id: "navbar-search-input", class: 'form-control', placeholder: 'Search Post Title.....'%>
<% end %>

<%= form_tag posts_path, :remote => true do %>
  <%= select_tag(:option, options_for_select([['Title', 'title'], ['Body', 'body'], ['Created', 'created_at']], :selected => params[:option]), { :include_blank => "Sort the Post",:id=> "post_select",:class=> "btn btn-default dropdown-toggle"}) %>
<% end %>

<h1>Listing posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id= "post_index">
    <%= render "post_list" %>  
  </tbody>
</table>
<br>
<% if can? :create, Post%>
  <%= link_to 'New Post', new_post_path, remote: true,:class=> "btn btn-primary" %>
<% end %>

<div id="post-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/posts/index.js.erb
$("#post_index").html("<%= j render :partial => 'post_list', :posts => @posts %>");

app/views/posts/new.js.erb
$("#post-modal").html("<%= escape_javascript(render 'new') %>")
$("#post-modal").modal("show")

app/views/posts/show.html.erb
<div style:"width: 25%">
  <h4><strong>Title:</strong></h4>
  <%= @post.title %> <br/>
  <h4><strong>Body:</strong></h4>
  <%= @post.body %>
</div><br/>
<div class= "pull-right" id="comment_div">
  <section class="panel panel-default">
    <h4 class="panel-heading" id= "post_count">Comments(<%= @post.comments.length %>)</h4>
    <div id="comments">
      <%= render @post.comments %>
    </div>
  </section>
</div>  
  <% if can? :create, Comment%>
    <section class="panel">
      <h4 class="panel-title">Add a comment:</h4>
      <%= render 'comments/form' %>
    </section>
  <% end %>

  <% if can? :edit, Post %>
    <%= link_to 'Edit', edit_post_path(@post), :class=>"btn btn-info" %>
  <% end %> |
  <%= link_to 'Back', posts_path,:class=> "btn btn-default" %>

app/views/posts/update.js.erb
<%= render "save" %>